# Generated by Django 5.0.4 on 2024-04-30 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignes', '0001_initial'),
        ('lignesAssignTo', '0002_lignesassignto_affectation_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lignesassignto',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lignesassignto',
            name='ligne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_assignments', to='lignes.ligne'),
        ),
        migrations.AlterField(
            model_name='lignesassignto',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
