# Generated by Django 5.0.4 on 2024-05-17 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignes', '0002_remove_ligne_daterealisation_ligne_sem_ligne_type_and_more'),
        ('lignesAssignTo', '0003_lignesassignto_confirmed_alter_lignesassignto_ligne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignesassignto',
            name='ligne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lignes.ligne'),
        ),
    ]
