# Generated by Django 5.0.4 on 2024-04-30 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lignes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LignesAssignto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('realisation_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('affectation_date', models.DateField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validateur_lignes_assignments', to='lignes.ligne')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validateur_technician_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VerificationFinal', models.BooleanField(default=False)),
                ('DateVerification', models.DateField(blank=True, null=True)),
                ('lignes_assignto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='validateur.lignesassignto')),
            ],
        ),
    ]
