# Generated by Django 5.0.4 on 2024-04-30 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignes', '0001_initial'),
        ('lignesAssignTo', '0003_lignesassignto_confirmed_alter_lignesassignto_ligne_and_more'),
        ('validateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LignesAssignto',
            new_name='ValidateurLignesAssignto',
        ),
        migrations.AlterField(
            model_name='verification',
            name='lignes_assignto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='lignesAssignTo.lignesassignto'),
        ),
    ]
