# Generated by Django 5.0.4 on 2024-04-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('daterealisation', models.DateField()),
                ('datecreation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
