# Generated by Django 5.0.4 on 2024-05-17 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne',
            name='daterealisation',
        ),
        migrations.AddField(
            model_name='ligne',
            name='sem',
            field=models.CharField(default='sem', max_length=50),
        ),
        migrations.AddField(
            model_name='ligne',
            name='type',
            field=models.CharField(default='Hebdo', max_length=50),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('realisation_date', models.DateField()),
                ('nbr_banc', models.IntegerField()),
                ('validatedByTechnicien', models.BooleanField(default=False)),
                ('validatedByValidator', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lignes.ligne')),
            ],
        ),
    ]
