# Generated by Django 5.0.4 on 2024-05-20 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignes', '0002_remove_ligne_daterealisation_ligne_sem_ligne_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='test',
            name='ligne',
        ),
        migrations.RemoveField(
            model_name='test',
            name='realisation_date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='validatedByTechnicien',
        ),
        migrations.RemoveField(
            model_name='test',
            name='validatedByValidator',
        ),
        migrations.CreateModel(
            name='LigneTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligne_tests', to='lignes.ligne')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_lignes', to='lignes.test')),
            ],
        ),
        migrations.CreateModel(
            name='Banc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banc_name', models.CharField(max_length=100)),
                ('validated_by_technician', models.BooleanField(default=False)),
                ('validated_by_validator', models.BooleanField(default=False)),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('revalidation_date', models.DateField(blank=True, null=True)),
                ('validator_visa', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('technician', models.ForeignKey(blank=True, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banc_technician_validations', to=settings.AUTH_USER_MODEL)),
                ('validator', models.ForeignKey(blank=True, limit_choices_to={'role': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banc_validator_validations', to=settings.AUTH_USER_MODEL)),
                ('ligne_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancs', to='lignes.lignetest')),
            ],
        ),
    ]
