# Generated by Django 5.0.4 on 2024-05-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignes', '0003_remove_test_comment_remove_test_ligne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne',
            name='type',
        ),
        migrations.AddField(
            model_name='lignetest',
            name='periodicity',
            field=models.CharField(default='Hebdo', max_length=100),
        ),
    ]
