# Generated by Django 5.0.4 on 2024-05-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignes', '0004_remove_ligne_type_lignetest_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='nbr_banc',
            field=models.IntegerField(default=0),
        ),
    ]
