# Generated by Django 5.0.4 on 2024-05-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignes', '0005_alter_test_nbr_banc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('en_cours', 'En cours'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
