# Generated by Django 5.0.4 on 2024-05-31 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lignes', '0006_ligne_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='banc',
            name='test',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='lignes.test'),
            preserve_default=False,
        ),
    ]
